spring.application.name=bank_rest
server.port=8081

spring.docker.compose.enabled=false

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bankdb
spring.datasource.username=bankuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA - ???? ????????
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml